substitutions:
  name: innova
  modbus_address: "0x0001"

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret esp_api_key

ota:
  password: !secret esp_ota
  platform: esphome

uart:
  tx_pin: GPIO01
  rx_pin: GPIO03
  baud_rate: 9600
  stop_bits: 1
  id: uart_bus

external_components:
  - source:
      type: git
      url: https://github.com/pico1881/Esphome-Innova-Climate-Wall-Panel
      ref: main
    components: [ innova_climate_wall ]

climate:
  - platform: innova_climate_wall
    name: ${name}
    address: ${modbus_address}
    update_interval: 30s
    
    #optional Air temperature sensor
    air_temperature:
      name: ${name} air temp
    #optional Temperature setpoint sensor    
    setpoint:
      name: ${name} setpoint   
    #optional switch for lock the on-board device keyboard 
    key_lock_switch:
      name: ${name} key lock
